language: java
jdk:
- oraclejdk8
sudo: false
# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

# prevent travis running gradle assemble; let the build script do it anyway
install: true

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

after_success:
  — bash <(curl -s https://codecov.io/bash)

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle



